def generate_template():
    return {
        "title": "Document title",
        "url": "Document download url if applicable",
        "type": "PDF",
        "page_count": 9,
        "sections": {
            "Positions": {
                "empty": None,
                "columns": ["Position", "Name of Organization"],
                "rows": {},
            },
            "Agreements": {
                "empty": True,
                "columns": ["Date", "Parties and Terms"],
                "rows": {},
            },
            "Non-Investment Income": {
                "empty": True,
                "columns": ["Date", "Source and Type", "Income"],
                "rows": {},
            },
            "Non Investment Income Spouse": {
                "empty": True,
                "columns": ["Date", "Source and Type"],
                "rows": {},
            },
            "Reimbursements": {
                "empty": True,
                "columns": [
                    "Source",
                    "Dates",
                    "Locations",
                    "Purpose",
                    "Items Paid or Provided",
                ],
                "rows": {},
            },
            "Gifts": {
                "empty": True,
                "columns": ["Source", "Description", "Value"],
                "rows": {},
            },
            "Liabilities": {
                "empty": True,
                "columns": ["Creditor", "Description", "Value Code"],
                "rows": {},
            },
            "Investments and Trusts": {
                "empty": True,
                "help": {
                    "A": "Description of Assets",
                    "B1": "Amount Code (A-H)",
                    "B2": "Type",
                    "C1": "Value Code 2",
                    "C2": "Value Method Code 3",
                    "D1": "Type",
                    "D2": "Date Month/Day",
                    "D3": "Value Code 2",
                    "D4": "Gain Code 1",
                    "D5": "Identity of Buyer/Seller (if private)",
                },
                "columns": [
                    "A",
                    "B1",
                    "B2",
                    "C1",
                    "C2",
                    "D1",
                    "D2",
                    "D3",
                    "D4",
                    "D5",
                ],
                "rows": {},
            },
        },
        "Additional Information or Explanations": {"text": None},
        "pdf_size": None,
        "date_created": None,
        "success": None,
        "msg": None,
    }
